### ISSUE TITLE
an administrator should be able to download files for printing

### ISSUE THREAD

**Issue by saibotsivad** [tobiaslabs/omaha3dprint.com#2]
Currently the site just saves the STL files in a folder, giving them unique filenames, and counts on the administrator knowing which file names go with each order and having FTP access to download the files.

Make some endpoint such that an administrator can download the file directly via HTTP, given some unique key. Obviously the key should have enough bits of entropy that it is not guessable, e.g. a randomly generated UUID is probably sufficient.

Still, client personal information should not be accessible this way, that information would be in the email sent to the administrator.

(Will the email login system @TehShrike is working on be functional? That might be ideal.)

**Comment by saibotsivad** [comment]
:stuck_out_tongue_winking_eye:

**Comment by pwnate** [comment]
How could you....?

-Nathan Davis
